comment: false

coverage:
  range: 50..90
  round: up
  precision: 3

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

codecov:
  require_ci_to_pass: yes
  after_n_builds: 3  # Ensures Codecov waits for all three OSs
